# Lightning node settings
[node]
network = "regtest"                           # Bitcoin network to use
listening_addresses = ["localhost:3001"]      # Lightning node listening addresses
announcement_addresses = ["54.3.7.81:3001"]   # Lightning node announcement addresses
#grpc_service_address = "127.0.0.1:3536"       # LDK Server gRPC address (optional, defaults to 127.0.0.1:3536)
alias = "ldk_server"                          # Lightning node alias
#pathfinding_scores_source_url = ""           # External Pathfinding Scores Source
#rgs_server_url = "https://rapidsync.lightningdevkit.org/snapshot/v2/"  # Optional: RGS URL for rapid gossip sync

# Storage settings
[storage.disk]
dir_path = "/tmp/ldk-server/"                 # Path for LDK and BDK data persistence, optional, defaults to ~/Library/Application Support/ldk-server/ on macOS, ~/.ldk-server/ on Linux

[log]
level = "Debug"                               # Log level (Error, Warn, Info, Debug, Trace)
file = "/tmp/ldk-server/ldk-server.log"       # Log file path

[tls]
#cert_path = "/path/to/tls.crt"               # Path to TLS certificate, by default uses dir_path/tls.crt
#key_path = "/path/to/tls.key"                # Path to TLS private key, by default uses dir_path/tls.key
hosts = ["example.com"]                       # Allowed hosts for TLS, will always include "localhost" and "127.0.0.1"

# Must set one of bitcoind, electrum, or esplora

# Bitcoin Core settings
[bitcoind]
rpc_address = "127.0.0.1:18444"               # RPC endpoint
rpc_user = "polaruser"                        # RPC username
rpc_password = "polarpass"                    # RPC password

# Electrum settings
[electrum]
server_url = "ssl://electrum.blockstream.info:50002"  # Electrum endpoint
# server_url = "tcp://electrum.blockstream.info:50001"

# Esplora settings
[esplora]
server_url = "https://mempool.space/api"      # Esplora endpoint

# LSPS2 Client Support
[liquidity.lsps2_client]
# The public key of the LSPS2 LSP we source just-in-time liquidity from.
node_pubkey = "<lsp node pubkey>"
# Address to connect to the LSPS2 LSP (IPv4:port, IPv6:port, OnionV3:port, or hostname:port).
address = "<lsp ip address>:9735"
# Optional token for authenticating to the LSP.
# token = ""

# Experimental LSPS2 Service Support
# CAUTION: LSPS2 support is highly experimental and for testing purposes only.
[liquidity.lsps2_service]
# Indicates whether the LSPS service will be announced via the gossip network.
advertise_service = false

# The fee we withhold for the channel open from the initial payment.
channel_opening_fee_ppm = 1000            # 0.1% fee

# The proportional overprovisioning for the channel.
channel_over_provisioning_ppm = 500000    # 50% extra capacity

# The minimum fee required for opening a channel.
min_channel_opening_fee_msat = 10000000   # 10,000 satoshis

# The minimum number of blocks after confirmation we promise to keep the channel open.
min_channel_lifetime = 4320               # ~30 days

# The maximum number of blocks that the client is allowed to set its `to_self_delay` parameter.
max_client_to_self_delay = 1440           # ~10 days

# The minimum payment size that we will accept when opening a channel.
min_payment_size_msat = 10000000          # 10,000 satoshis

# The maximum payment size that we will accept when opening a channel.
max_payment_size_msat = 25000000000       # 0.25 BTC

# Use the 'client-trusts-LSP' trust model.
# When set, the service will delay broadcasting the JIT channel's
# funding transaction until the client claimed sufficient HTLC parts to pay for the channel open.
client_trusts_lsp = false

# Allow the LSP clients to keep zero channel reserves, i.e., spend their full balance.
# Note this will potentially allow them to attempt cheating without risking financial penalty, so
# this should only be set if you understand the risk and trust you clients.
allow_client_0reserve = false

# Optional token for clients (uncomment and set if required)
## A token we may require to be sent by the clients.
## If set, only requests matching this token will be accepted. (uncomment and set if required)
# require_token = ""

# Metrics settings
[metrics]
enabled = false
poll_metrics_interval = 60       # The polling interval for metrics in seconds. Defaults to 60secs if unset and metrics enabled.
# The auth details below are optional, but uncommenting the fields means enabling basic auth, so valid fields must be supplied.
#username = ""               # The username required to access the metrics endpoint (Basic Auth).
#password = ""               # The password required to access the metrics endpoint (Basic Auth).

# Tor Config
[tor]
# Only connections to OnionV3 peers will be made via this proxy; other connections (IPv4 peers, Electrum server) will not be routed over Tor.
#proxy_address = ""      # Tor daemon SOCKS proxy address.
